// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodecProviderKind } from "./CodecProviderKind";
import type { ExportPreset } from "./ExportPreset";

export type CodecCapability = { schema_version: number, provider: CodecProviderKind, preset: ExportPreset, video_supported: boolean, audio_supported: boolean, streaming_sink_supported: boolean, };
