import type {
	BundleEntry,
	BundleEntryReceipt,
	EditableCampaignBundle,
	StagedCampaignImport,
	StudioState,
} from "@variantlab/studio-contract";
import { renderValidateBundleReceipts } from "variantlab-wasm";
import { planMediaDerivatives, snapshotHash } from "./domain";
import { createStoredCampaign, deleteStoredCampaign } from "./local-store";
import {
	commitStagedOriginalWithReceipt,
	deleteMediaAssetsForCampaign,
	fileForPath,
	fileHandleForPath,
	listMediaAssets,
	removeArtifact,
	removeCommittedOriginalIfUnreferenced,
	saveMediaAsset,
	stageOriginal,
	type CommittedOriginalReceipt,
	type StagedOriginal,
	type StoredMediaAsset,
} from "./media-store";
import { probeMediaFile } from "./media-probe";

const MAGIC = new TextEncoder().encode("VLBUNDLE1");
const MAX_HEADER_BYTES = 16 * 1024 * 1024;

type BundleMediaProvenance = {
	schema_version: 1;
	source: "local-import";
	scene_id: string;
	name: string;
	declared_mime: string;
	detected_mime: string;
};

function bundleMediaProvenance(asset: StoredMediaAsset): string {
	return JSON.stringify({
		schema_version: 1,
		source: "local-import",
		scene_id: asset.scene_id,
		name: asset.name,
		declared_mime: asset.declared_mime,
		detected_mime: asset.detected_mime,
	} satisfies BundleMediaProvenance);
}

function parseBundleMediaProvenance(value: string): BundleMediaProvenance {
	const parsed: unknown = JSON.parse(value);
	if (
		typeof parsed !== "object" ||
		parsed === null ||
		!("schema_version" in parsed) ||
		parsed.schema_version !== 1 ||
		!("source" in parsed) ||
		parsed.source !== "local-import" ||
		!("scene_id" in parsed) ||
		typeof parsed.scene_id !== "string" ||
		!("name" in parsed) ||
		typeof parsed.name !== "string" ||
		!("declared_mime" in parsed) ||
		typeof parsed.declared_mime !== "string" ||
		!("detected_mime" in parsed) ||
		typeof parsed.detected_mime !== "string"
	) {
		throw new Error("Editable campaign bundle media provenance is malformed");
	}
	return {
		schema_version: 1,
		source: "local-import",
		scene_id: parsed.scene_id,
		name: parsed.name,
		declared_mime: parsed.declared_mime,
		detected_mime: parsed.detected_mime,
	};
}

function uint32(value: number): Uint8Array<ArrayBuffer> {
	const bytes = new Uint8Array(new ArrayBuffer(4));
	new DataView(bytes.buffer).setUint32(0, value, true);
	return bytes;
}

function parseImportedState(json: string): StudioState {
	const value: unknown = JSON.parse(json);
	if (
		typeof value !== "object" ||
		value === null ||
		!("campaign" in value) ||
		typeof value.campaign !== "object" ||
		value.campaign === null
	) {
		throw new Error("Rust returned an invalid imported campaign state");
	}
	// This is generated by the Rust validator from a validated StudioState.
	// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
	return value as StudioState;
}

function validateReceipts({
	bundle,
	receipts,
	newCampaignId,
}: {
	bundle: EditableCampaignBundle;
	receipts: BundleEntryReceipt[];
	newCampaignId: string;
}): StagedCampaignImport {
	const value: unknown = JSON.parse(
		renderValidateBundleReceipts(
			JSON.stringify(bundle),
			JSON.stringify(receipts),
			newCampaignId,
		),
	);
	if (
		typeof value !== "object" ||
		value === null ||
		!("imported_state_json" in value)
	) {
		throw new Error("Rust returned an invalid staged bundle receipt");
	}
	// Rust is the source of truth and emitted this generated contract.
	// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
	return value as StagedCampaignImport;
}

export async function exportEditableCampaignBundle(
	state: StudioState,
): Promise<{
	artifactPath: string;
	filename: string;
	byteLength: number;
	bundle: EditableCampaignBundle;
}> {
	const assets = (await listMediaAssets(state.campaign.id)).toSorted(
		(left, right) => left.asset_hash.localeCompare(right.asset_hash),
	);
	const uniqueAssets = new Map(
		assets.map((asset) => [asset.asset_hash, asset]),
	);
	const entries: BundleEntry[] = Array.from(uniqueAssets.values()).map(
		(asset) => ({
			path: `media/${asset.asset_hash}`,
			compressed_bytes: asset.byte_length,
			expanded_bytes: asset.byte_length,
			sha256: asset.asset_hash,
			provenance: bundleMediaProvenance(asset),
		}),
	);
	const bundle: EditableCampaignBundle = {
		schema_version: 1,
		snapshot_json: JSON.stringify(state),
		snapshot_sha256: snapshotHash(state),
		entries,
	};
	const header = new TextEncoder().encode(JSON.stringify(bundle));
	if (header.byteLength > MAX_HEADER_BYTES) {
		throw new Error("Editable bundle header exceeds the 16 MiB safety limit");
	}
	const filename = `${state.campaign.name.trim().replaceAll(/[^\p{L}\p{N}._-]+/gu, "_") || "campaign"}.vlcampaign`;
	const artifactPath = `bundles/${state.campaign.id}-${state.campaign.revision}.vlcampaign`;
	await removeArtifact(artifactPath).catch(() => undefined);
	const handle = await fileHandleForPath({ path: artifactPath, create: true });
	const writable = await handle.createWritable({ keepExistingData: false });
	try {
		await writable.write(MAGIC);
		await writable.write(uint32(header.byteLength));
		await writable.write(header);
		for (const asset of uniqueAssets.values()) {
			const source = await fileForPath(asset.original_path);
			const reader = source.stream().getReader();
			try {
				while (true) {
					const result = await reader.read();
					if (result.done) break;
					await writable.write(result.value);
				}
			} finally {
				reader.releaseLock();
			}
		}
		await writable.close();
	} catch (error) {
		await writable.abort(error).catch(() => undefined);
		await removeArtifact(artifactPath).catch(() => undefined);
		throw error;
	}
	const result = await handle.getFile();
	return { artifactPath, filename, byteLength: result.size, bundle };
}

export type BundleImportFailurePoint =
	| "after_existing_original_commit"
	| "after_first_original_commit"
	| "after_provenance"
	| "after_probe"
	| "after_first_media_commit"
	| "after_campaign_commit";

export function bundleImportFailurePointFromValue(
	value: string,
): BundleImportFailurePoint | undefined {
	switch (value) {
		case "after_existing_original_commit":
		case "after_first_original_commit":
		case "after_provenance":
		case "after_probe":
		case "after_first_media_commit":
		case "after_campaign_commit":
			return value;
		default:
			return undefined;
	}
}

function injectBundleImportFailure({
	configured,
	point,
}: {
	configured: BundleImportFailurePoint | undefined;
	point: BundleImportFailurePoint;
}): void {
	if (configured === point) {
		throw new Error(`Injected editable bundle import failure: ${point}`);
	}
}

export async function importEditableCampaignBundle({
	file,
	newCampaignId,
	failurePoint,
}: {
	file: File;
	newCampaignId: string;
	failurePoint?: BundleImportFailurePoint;
}): Promise<StudioState> {
	const prefix = new Uint8Array(
		await file.slice(0, MAGIC.byteLength + 4).arrayBuffer(),
	);
	if (
		prefix.byteLength !== MAGIC.byteLength + 4 ||
		!MAGIC.every((byte, index) => prefix[index] === byte)
	) {
		throw new Error("Unknown editable campaign bundle format");
	}
	const headerLength = new DataView(prefix.buffer).getUint32(
		MAGIC.byteLength,
		true,
	);
	if (headerLength <= 0 || headerLength > MAX_HEADER_BYTES) {
		throw new Error("Editable campaign bundle header is outside safety limits");
	}
	const bodyOffset = MAGIC.byteLength + 4 + headerLength;
	if (bodyOffset > file.size)
		throw new Error("Editable campaign bundle is truncated");
	const headerJson = await file.slice(MAGIC.byteLength + 4, bodyOffset).text();
	const parsed: unknown = JSON.parse(headerJson);
	if (typeof parsed !== "object" || parsed === null || !("entries" in parsed)) {
		throw new Error("Editable campaign bundle manifest is malformed");
	}
	// The value is immediately validated by Rust before any campaign is committed.
	// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
	const bundle = parsed as EditableCampaignBundle;
	const declaredReceipts = bundle.entries.map((entry) => ({
		path: entry.path,
		expanded_bytes: entry.expanded_bytes,
		sha256: entry.sha256,
	}));
	validateReceipts({ bundle, receipts: declaredReceipts, newCampaignId });

	let offset = bodyOffset;
	const staged: Array<{
		original: StagedOriginal;
		receipt: BundleEntryReceipt;
	}> = [];
	const committed = new Map<string, CommittedOriginalReceipt>();
	let provenanceChecked = false;
	let probeChecked = false;
	let mediaCommitted = false;
	try {
		for (const [index, entry] of bundle.entries.entries()) {
			const end = offset + entry.expanded_bytes;
			if (end > file.size)
				throw new Error("Editable campaign bundle has a missing asset");
			const part = new File([file.slice(offset, end)], entry.path, {
				type: "application/octet-stream",
			});
			const original = await stageOriginal({
				file: part,
				stagingId: `bundle-${newCampaignId}-${index}`,
			});
			staged.push({
				original,
				receipt: {
					path: entry.path,
					expanded_bytes: original.byteLength,
					sha256: original.assetHash,
				},
			});
			offset = end;
		}
		if (offset !== file.size)
			throw new Error("Editable campaign bundle has trailing entries");
		const validated = validateReceipts({
			bundle,
			receipts: staged.map((entry) => entry.receipt),
			newCampaignId,
		});
		for (const entry of staged) {
			if (!committed.has(entry.original.assetHash)) {
				const receipt = await commitStagedOriginalWithReceipt(entry.original);
				committed.set(entry.original.assetHash, receipt);
				if (!receipt.created) {
					injectBundleImportFailure({
						configured: failurePoint,
						point: "after_existing_original_commit",
					});
				}
				if (committed.size === 1) {
					injectBundleImportFailure({
						configured: failurePoint,
						point: "after_first_original_commit",
					});
				}
			}
		}
		const state = parseImportedState(validated.imported_state_json);
		for (const [index, entry] of bundle.entries.entries()) {
			const stagedEntry = staged[index];
			if (!stagedEntry) throw new Error("Validated media receipt is missing");
			const metadata = parseBundleMediaProvenance(entry.provenance);
			if (!provenanceChecked) {
				provenanceChecked = true;
				injectBundleImportFailure({
					configured: failurePoint,
					point: "after_provenance",
				});
			}
			if (
				metadata.detected_mime !== stagedEntry.original.detectedMime ||
				!state.campaign.master_sequence.scenes.some(
					(scene) => scene.id === metadata.scene_id,
				)
			) {
				throw new Error("Editable campaign bundle media provenance is invalid");
			}
			const receipt = committed.get(stagedEntry.original.assetHash);
			if (!receipt) throw new Error("Committed media path is missing");
			const probe = await probeMediaFile({
				file: await fileForPath(receipt.path),
				assetHash: stagedEntry.original.assetHash,
				declaredMime: metadata.declared_mime,
				detectedMime: metadata.detected_mime,
			});
			if (!probeChecked) {
				probeChecked = true;
				injectBundleImportFailure({
					configured: failurePoint,
					point: "after_probe",
				});
			}
			await saveMediaAsset({
				asset_id: `${state.campaign.id}:${stagedEntry.original.assetHash}`,
				campaign_id: state.campaign.id,
				scene_id: metadata.scene_id,
				asset_hash: stagedEntry.original.assetHash,
				name: metadata.name,
				declared_mime: metadata.declared_mime,
				detected_mime: metadata.detected_mime,
				byte_length: stagedEntry.original.byteLength,
				original_path: receipt.path,
				probe,
				plan: planMediaDerivatives(probe),
				created_at: state.campaign.updated_at,
			});
			if (!mediaCommitted) {
				mediaCommitted = true;
				injectBundleImportFailure({
					configured: failurePoint,
					point: "after_first_media_commit",
				});
			}
		}
		await createStoredCampaign({ state });
		injectBundleImportFailure({
			configured: failurePoint,
			point: "after_campaign_commit",
		});
		return state;
	} catch (error) {
		const rollbackFailures: unknown[] = [];
		for (const rollback of [
			() => deleteStoredCampaign(newCampaignId),
			() => deleteMediaAssetsForCampaign(newCampaignId),
		]) {
			try {
				await rollback();
			} catch (rollbackError) {
				rollbackFailures.push(rollbackError);
			}
		}
		for (const receipt of committed.values()) {
			try {
				await removeCommittedOriginalIfUnreferenced(receipt);
			} catch (rollbackError) {
				rollbackFailures.push(rollbackError);
			}
		}
		for (const entry of staged) {
			try {
				await removeArtifact(entry.original.stagingPath);
			} catch (rollbackError) {
				if (
					!(rollbackError instanceof DOMException) ||
					rollbackError.name !== "NotFoundError"
				) {
					rollbackFailures.push(rollbackError);
				}
			}
		}
		if (rollbackFailures.length > 0) {
			throw new AggregateError(
				[error, ...rollbackFailures],
				"Editable bundle import failed and rollback was incomplete",
			);
		}
		throw error;
	}
}
