// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvenanceSource = "master" | "delivery_profile" | "variant_cell" | "creative_set" | "brand_kit";
