// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";

export type VariantDiagnostic = { code: string, severity: DiagnosticSeverity, message: string, action: string, };
