// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvenanceEntry } from "./ProvenanceEntry";
import type { VariantCellStatus } from "./VariantCellStatus";
import type { VariantProjectionDiagnostic } from "./VariantProjectionDiagnostic";

export type VariantProjectionItem = { cell_id: string, creative_set_id: string, delivery_profile_id: string, status: VariantCellStatus, diagnostics: Array<VariantProjectionDiagnostic>, provenance: Array<ProvenanceEntry>, fingerprint: string, };
