// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFailure } from "./JobFailure";

export type JobEvent = { "event": "start_preparing" } | { "event": "start_running" } | { "event": "progress", phase: string, completed_units: number, total_units: number, } | { "event": "request_pause" } | { "event": "confirm_paused" } | { "event": "resume" } | { "event": "request_cancel" } | { "event": "confirm_cancelled" } | { "event": "succeed", artifact_path: string, } | { "event": "fail", failure: JobFailure, } | { "event": "recover_after_reload" } | { "event": "retry" };
