// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";

export type JobSpec = { schema_version: number, job_id: string, campaign_id: string, asset_hash: string, kind: JobKind, idempotency_key: string, engine_version: string, normalized_options_json: string, priority: number, };
