// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadPartReceipt } from "./UploadPartReceipt";

export type MultipartUploadSession = { schema_version: number, upload_id: string, tenant_id: string, campaign_id: string, asset_hash: string, object_key: string, total_bytes: number, part_size_bytes: number, completed_parts: Array<UploadPartReceipt>, expires_at: string, };
