// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFailure } from "./JobFailure";
import type { RenderPhase } from "./RenderPhase";

export type RenderJobEvent = { "event": "start" } | { "event": "progress", phase: RenderPhase, progress_milli: number, } | { "event": "cancel" } | { "event": "confirm_cancelled" } | { "event": "fail", failure: JobFailure, } | { "event": "succeed", artifact_path: string, } | { "event": "recover_after_reload" } | { "event": "retry" } | { "event": "mark_stale" };
