// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timeline } from "./Timeline";

export type TimelineEditResult = { timeline: Timeline, changed_clip_ids: Array<string>, dirty_start_ticks: number, dirty_end_ticks: number, snapped_to_ticks: number | null, };
