// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineClip } from "./TimelineClip";
import type { TrackKind } from "./TrackKind";

export type TimelineTrack = { id: string, name: string, kind: TrackKind, height: number, clips: Array<TimelineClip>, };
