// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineTrack } from "./TimelineTrack";

export type Timeline = { fps_num: number, fps_den: number, duration_ticks: number, tracks: Array<TimelineTrack>, };
