// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipPlacement } from "./ClipPlacement";

export type TimelinePreviewResult = { placements: Array<ClipPlacement>, removed_clip_ids: Array<string>, snapped_to_ticks: number | null, };
