// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VisibleTimelineQuery = { start_ticks: number, end_ticks: number, first_track: number, last_track: number, overscan_ticks: number, max_nodes: number, };
