FROM rust:1.91.1-bookworm@sha256:c1e5f19e773b7878c3f7a805dd00a495e747acbdc76fb2337a4ebf0418896b33

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        libxkbcommon-dev \
        libxkbcommon-x11-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add wasm32-unknown-unknown \
    && cargo install wasm-pack --version 0.13.1 --locked

RUN rustup component add clippy rustfmt

WORKDIR /workspace
