// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlotValue = { "kind": "media", asset_id: string, duration_ticks: number, } | { "kind": "text", text: string, } | { "kind": "logo", asset_id: string, };
