[package]
name = "edit-engine"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
creative-engine = { version = "0.1.0", path = "../creative-engine" }
serde_json = "1.0.145"
studio-model = { version = "0.1.0", path = "../studio-model" }
transcript-engine = { version = "0.1.0", path = "../transcript-engine" }
thiserror = "2.0.18"
timeline-engine = { version = "0.1.0", path = "../timeline-engine" }
variant-engine = { version = "0.1.0", path = "../variant-engine" }
