// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderTiming } from "./RenderTiming";

export type DeliverableArtifact = { cell_id: string, campaign_revision: number, preset: string, filename: string, media_type: string, byte_length: number, sha256: string, render_manifest_sha256: string, timing: RenderTiming, };
