// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coordinates in 1/10000 of the output canvas, all supplied explicitly.
 */
export type PlacementRect = { x: number, y: number, width: number, height: number, };
