// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderOverlay = { slot_id: string, x: number, y: number, width: number, height: number, z_index: number, start_tick: number, end_tick: number, };
