// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackKind } from "./TrackKind";

export type RenderClipNode = { scene_id: string, clip_id: string, asset_hash: string, track_kind: TrackKind, has_audio: boolean, start_tick: number, duration_ticks: number, source_offset_ticks: number, source_duration_ticks: number, };
