// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotRenderTarget } from "./SlotRenderTarget";
import type { SlotValue } from "./SlotValue";

export type RenderSlotNode = { slot_id: string, value: SlotValue, target: SlotRenderTarget, };
