// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlignment } from "./TextAlignment";

export type RenderTextStyle = { font_id: string, font_sha256: string, font_size_px: number, line_height_px: number, max_lines: number, color_rgba: [number, number, number, number], alignment: TextAlignment, };
