// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SafeArea = { top_basis_points: number, right_basis_points: number, bottom_basis_points: number, left_basis_points: number, };
