// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlacementRect } from "./PlacementRect";
import type { RenderTextStyle } from "./RenderTextStyle";

export type SlotRenderTarget = { "kind": "clip", scene_id: string, clip_id: string, } | { "kind": "overlay", scene_id: string, start_ticks: number, end_ticks: number, rect: PlacementRect, z_index: number, text_style: RenderTextStyle | null, };
