// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProxyTier = { tier: string, max_width: number, max_height: number, video_bitrate: number, video_codec: string, audio_codec: string, keyframe_interval_ticks: number, };
