// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaveformLevelSpec } from "./WaveformLevelSpec";

export type WaveformSpec = { channels: number, base_samples_per_bucket: number, levels: Array<WaveformLevelSpec>, values: Array<string>, };
